/**
 * send-invitation — Supabase Edge Function (Deno runtime)
 *
 * Inserts an invitation row and emails the invitee via the Resend API.
 *
 * Request: POST /send-invitation
 *   Body: { "inviteeEmail": "<email>" }
 *   Headers: Authorization: Bearer <user JWT>
 *
 * Response: { "success": true, "invitationId": "<UUID>" }
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')!;

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS });
  }

  try {
    if (!RESEND_API_KEY) throw new Error('RESEND_API_KEY secret is not configured');

    // Authenticate the caller
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('Missing authorization header');

    const anonClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const {
      data: { user },
      error: authError,
    } = await anonClient.auth.getUser(authHeader.replace('Bearer ', ''));
    if (authError || !user) throw new Error('Unauthorized');

    const serviceClient = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

    // Get inviter profile
    const { data: inviterProfile } = await serviceClient
      .from('profiles')
      .select('display_name, role')
      .eq('id', user.id)
      .single();

    const { inviteeEmail } = await req.json();
    if (!inviteeEmail || typeof inviteeEmail !== 'string') {
      throw new Error('inviteeEmail is required');
    }

    // Landlord invites tenant; tenant invites landlord
    const roleToGive = inviterProfile?.role === 'landlord' ? 'tenant' : 'landlord';

    // Insert the invitation — token and expires_at are generated by the DB
    const { data: invitation, error: invErr } = await serviceClient
      .from('invitations')
      .insert({
        inviter_id: user.id,
        invitee_email: inviteeEmail.trim().toLowerCase(),
        role_to_give: roleToGive,
        status: 'pending',
      })
      .select('id, token')
      .single();

    if (invErr) throw new Error(invErr.message);

    // Send invitation email via Resend
    const inviterName = inviterProfile?.display_name ?? 'Someone';
    const deepLink = `tenant-guardian://invite?token=${invitation.token}`;
    const roleLabel = roleToGive === 'tenant' ? 'a tenant' : 'a property manager';

    const emailRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: Deno.env.get('EMAIL_FROM') ?? 'Tenant Guardian <onboarding@resend.dev>',
        to: [inviteeEmail.trim()],
        subject: `${inviterName} invited you to Tenant Guardian`,
        html: `
          <p>Hi,</p>
          <p><strong>${inviterName}</strong> has invited you to connect on <strong>Tenant Guardian</strong> as ${roleLabel}.</p>
          <p>Tap the link below on your phone to accept the invitation:</p>
          <p><a href="${deepLink}">Accept Invitation</a></p>
          <p>This invitation expires in 7 days. If you don't have the Tenant Guardian app yet, download it first and create an account.</p>
          <p style="color:#6b7280;font-size:12px;">If you weren't expecting this invitation, you can safely ignore this email.</p>
        `,
      }),
    });

    if (!emailRes.ok) {
      let emailErrMsg = `Resend HTTP ${emailRes.status}`;
      try {
        const body = await emailRes.json();
        if (body?.message) emailErrMsg = `Resend: ${body.message}`;
        else if (body?.name) emailErrMsg = `Resend: ${body.name}`;
      } catch {
        emailErrMsg = await emailRes.text().catch(() => emailErrMsg);
      }
      throw new Error(emailErrMsg);
    }

    return new Response(JSON.stringify({ success: true, invitationId: invitation.id }), {
      headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : 'Unknown error' }),
      { status: 400, headers: { 'Content-Type': 'application/json', ...CORS_HEADERS } },
    );
  }
});
